version: 1.0.{build}

pull_requests:
  do_not_increment_build_number: true

environment:
  source_dir: public
  git_name: Matt Horgan
  git_email: matt@matthorgan.xyz
  target_dir: temp
  target_branch: master
  repo: https://github.com/matthorgan/matthorgan.github.io.git
  access_token:
    secure: RcRrztcM59Im5xl40yelyNPtMZ8ydkEtFQ8nzen+4tcId4U8eT8yrTxTDOyUnJZu

install:
  - cmd: cinst hugo

build_script:
  - cmd: hugo

test: off

# Add newly built site to the master branch 
on_success:
 - cmd: git config --global credential.helper store 
 - ps: Add-Content "$env:userprofile\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
 - ps: $revision = git rev-parse HEAD
 - ps: New-Item -Path $env:target_dir -ItemType Directory
 - cmd: git clone --branch $env:target_branch $env:repo $env:target_dir 
 - ps: Copy-Item -Path .\$env:source_dir\* -Destination $env:target_dir -Recurse -Force -Exclude @(".git","appveyor.yml")
 - ps: cd $env:target_dir
 - cmd: git config --global user.name $env:git_name
 - cmd: git config --global user.email $env:git_email
 - cmd: git add --all 
 - cmd: git commit --allow-empty -m "Built from commit $revision
 - cmd: git push $repo $env:target_branch 