version: 1.0.{build}

pull_requests:
  do_not_increment_build_number: true

environment:
  source_dir: public
  git_name: Matt Horgan
  git_email: matt@matthorgan.xyz
  target_dir: temp
  target_branch: main
  repo: https://github.com/matthorgan/matthorgan.github.io.git
  access_token:
    secure: vIYO0we1IRXxWFw1Wx6Bhz4z9okRCHe+SuCVKPkMrP7rKIzlfChq15mfOAZ5UoIu

install:
  - cmd: cinst hugo
  - git submodule update --init --recursive

build_script:
  - cmd: hugo

# Add newly built site to the master branch
on_success:
  - ps: |
      Invoke-Expression "git config --global credential.helper store" 2>&1
      Add-Content "$env:userprofile\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
      $revision = Invoke-Expression "git rev-parse HEAD" 2>&1
      New-Item -Path $env:target_dir -ItemType Directory
      cd .\$env:target_dir
      Invoke-Expression "git clone --branch $env:target_branch $env:repo (Get-Location).Path" 2>&1
      #Invoke-Expression "git submodule add https://github.com/koirand/pulp.git themes/pulp" 2>&1
      Copy-Item -Path ..\$env:source_dir\* -Destination . -Recurse -Force -Exclude @(".git","appveyor.yml")
      Invoke-Expression "git config --global user.name $env:git_name" 2>&1
      Invoke-Expression "git config --global user.email $env:git_email" 2>&1
      Invoke-Expression "git add --all" #2>&1
      Invoke-Expression "git commit --allow-empty -m 'Built from commit $revision'" #2>&1
      Invoke-Expression "git push origin $env:target_branch" #2>&1
