baseurl = "https://matthorgan.github.io"
title = "Matt Horgan"
theme = "hugo-theme-nix"
languageCode = "en-us"
disqusShortname = "matthorgan"

[menu]
  [[menu.header]]
    name = "blog"
    weight = 0
    url = "/blog"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "/about"

[params]
  GithubID = "matthorgan"
  LinkedInID = "matthorganuk"
  Name = "Matt Horgan"
  HeaderUsername = "hugo"
  HeaderHostname = "matthorgan.xyz"
  Email = "matt@matthorgan.xyz"
  About = "I'm Matt, an Infrastructure Engineer from Bristol. I have a passion for automation using PowerShell and WinOps focused tools. Please feel free to get in contact with me using one of the links above!"
  ProfilePicture = "/blog-profile-picture.jpg"

