baseurl = "https://matthorgan.github.io"
title = "Matt Horgan"
theme = "hugo-theme-nix"
languageCode = "en-us"
disqusShortname = "matthorgan"
googleAnalytics = "UA-112770718-1"

[menu]
  [[menu.header]]
    name = "blog"
    weight = 0
    url = "/blog"

[params]
  GithubID = "matthorgan"
  LinkedInID = "matthorganuk"
  Name = "Matt Horgan"
  HeaderUsername = "hugo"
  HeaderHostname = "matthorgan.xyz"
  Email = "matt@matthorgan.xyz"
  About = "I'm Matt, a DevOps Engineer from Bristol. I have a passion for automating Infrastructure using PowerShell and DevOps tools. Please feel free to get in contact with me using one of the links above!"
  ProfilePicture = "/blog-profile-picture.jpg"

